global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'instance', 'job']
 # group_wait: 30s
 # group_interval: 1m
 # repeat_interval: 1m
  receiver: 'shahr-bank'

  routes:

    - match_re:

        app_type: (site|ssl)

      receiver: 'shahr-bank'

      routes:

      - match:

          app_type: site

        receiver: 'shahr-bank'

        group_wait: 1m

        group_interval: 5m

        repeat_interval: 30m

      - match:

          app_type: ssl

        receiver: 'shahr-bank'

        group_wait: 1m

        group_interval: 5m

        repeat_interval: 120h
receivers:
- name: 'shahr-bank'
  webhook_configs:
   - url: 'http://10.211.51.7:12001/SendAlert'
 # - url: 'http://127.0.0.1:1880/prometheus/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

