global:
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.211.51.7:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.211.51.7:9100']

  - job_name: 'blackbox'
    scrape_interval: 10s
    metrics_path: /probe
    file_sd_configs:
    - files:
      - 'targets/blackbox_targets/*.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.211.51.7:9115


  - job_name: 'ipmi-exporter'
#    scrape_interval: 1m
#    scrape_timeout: 30s
#    metrics_path: /ipmi
#    scheme: http
#    file_sd_configs:
#    - files:
#      - 'targets/ipmi-targets.yml'
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [module]
#        target_label: __param_module
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: 10.211.51.7:9290

  - job_name: 'snmp-exporter'
    scrape_interval: 30s
    scrape_timeout: 20s
    metrics_path: /snmp
    params:
      module: [if_mib]
    file_sd_configs:
    - files:
      - 'targets/snmp_targets/cisco.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 10.211.51.7:9116

#  - job_name: 'mikrotik-exporter'
#    static_configs:
#      - targets: ['localhost:9436']
#
